language: minimal

notifications:
  email: false

script:
   - docker build -t osirixfoundation/irdbb-reverse-proxy:$TRAVIS_BRANCH .
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

after_success:
   - docker push osirixfoundation/irdbb-reverse-proxy:$TRAVIS_BRANCH